# OpenAPI specification of devon4quarkus product service https://github.com/devonfw-sample/devon4quarkus-reference
# Used by openapi-generator-maven-plugin to generate the corresponding API for the rest client
---
openapi: 3.0.3
info:
  title: Product Service
  contact:
    name: Devonfw Support
  version: 1.0.0
tags:
- name: product
  description: Product API.
paths:
  /product/v1:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageProductDto'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDto'
      responses:
        "200":
          description: OK
  /product/v1/search:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductSearchCriteriaDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageProductDto'
  /product/v1/title/{title}:
    get:
      parameters:
      - name: title
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
  /product/v1/{id}:
    get:
      parameters:
      - name: id
        in: path
        description: Product unique id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
    delete:
      parameters:
      - name: id
        in: path
        description: Product unique id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
components:
  schemas:
    PageProductDto:
      type: array
      items:
        $ref: '#/components/schemas/ProductDto'
    ProductDto:
      type: object
      properties:
        id:
          format: int64
          type: integer
        modificationCounter:
          format: int32
          type: integer
        description:
          description: Product description
          maxLength: 500
          minLength: 3
          type: string
        price:
          description: Product price
          type: number
        title:
          description: Product title
          maxLength: 500
          minLength: 3
          type: string
          nullable: false
    ProductSearchCriteriaDto:
      type: object
      properties:
        determineTotal:
          description: determine total
          type: boolean
        pageNumber:
          format: int32
          description: Page Number
          default: "0"
          type: integer
        pageSize:
          format: int32
          description: Page Size
          default: "10"
          type: integer
        price:
          description: Product price
          type: number
        priceMax:
          description: Product Max price
          type: number
        priceMin:
          description: Product Min price
          type: number
        title:
          description: Product title
          type: string